login_btn = "Войти"
logout_btn = "Выйти"
ok_btn = "Ok"
cancel_btn = "Отмена"
accept_btn = "Принять"
reject_btn = "Отклонить"
yes_btn = "Да"
no_btn = "Нет"
open_btn = "Открыть"
close_btn = "Закрыть"
save_btn = "Сохранить"
