login_btn = "Login"
logout_btn = "Logout"
ok_btn = "Ok"
cancel_btn = "Cancel"
accept_btn = "Accept"
reject_btn = "Reject"
yes_btn = "Yes"
no_btn = "No"
open_btn = "Open"
close_btn = "Close"
save_btn = "Save"
